---
kiosk_user: hal9k
kiosk_browser: firefox
kiosk_browser_cmd: "firefox -new-window -kiosk"

kiosk_urls:
  - "file:///home/{{ kiosk_user }}/clock/index.html"
  - "http://localhost:8080/vejr"
  - "https://hal9k.dk/"
  - "http://localhost:8080/status"
