---
- name: Restart serve.service
  systemd:
    name: serve.service
    state: restarted
    scope: user
  become: true
  become_user: "{{ kiosk_user }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ kiosk_user_uid | default(1000) }}"

- name: Restart kiosk.service
  systemd:
    name: kiosk.service
    state: restarted
    scope: user
  become: true
  become_user: "{{ kiosk_user }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ kiosk_user_uid | default(1000) }}"
